server:
  port: 8000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: RESTAURANT-SEARCH-SERVICE
          uri: lb://RESTAURANT-SEARCH-SERVICE
          predicates:
            - Path=/restaurants/**, /foodItem/**
          filters:
            - name: CircuitBreaker
              args:
                  name: RESTAURANT-SEARCH-SERVICE
                  fallbackUri: forward:/restaurantServiceFallback
        - id: ORDER-MANAGEMENT-SERVICE
          uri: lb://ORDER-MANAGEMENT-SERVICE
          predicates:
            - Path=/orders/**, /orderItem/**

hystrix:
  command:
    fallbackcmd:
      execution:
        isolationthread:
          timeoutInMilliSeconds: 400

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost